version: '3'
services:
  database:
    image: pmunoz/genieus-db:development
    ports:
      - 5432:5432

  api:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/genieus-api
    depends_on:
      - database
